"""delete buying column

Revision ID: 1a567ee24848
Revises: f7d859848f3a
Create Date: 2024-06-22 14:39:27.242800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1a567ee24848'
down_revision: Union[str, None] = 'f7d859848f3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buying', 'phone')
    op.drop_column('buying', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buying', sa.Column('address', mysql.VARCHAR(length=30), nullable=True))
    op.add_column('buying', sa.Column('phone', mysql.VARCHAR(length=50), nullable=False))
    # ### end Alembic commands ###
