"""Update like game

Revision ID: 2719e05e720d
Revises: cb26730d41c8
Create Date: 2024-08-01 13:59:54.383891

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2719e05e720d'
down_revision: Union[str, None] = 'cb26730d41c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'description',
               existing_type=mysql.VARCHAR(length=10000),
               type_=sa.String(length=16000),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'description',
               existing_type=sa.String(length=16000),
               type_=mysql.VARCHAR(length=10000),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    # ### end Alembic commands ###
