"""test

Revision ID: 6f74b665d541
Revises: 4ef74bfbcfa0
Create Date: 2024-08-30 00:38:39.400511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6f74b665d541'
down_revision: Union[str, None] = '4ef74bfbcfa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'description',
               existing_type=mysql.VARCHAR(length=16000),
               type_=sa.String(length=14000),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('games', 'description',
               existing_type=sa.String(length=14000),
               type_=mysql.VARCHAR(length=16000),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    # ### end Alembic commands ###
