"""update time buying

Revision ID: d3aab22d4830
Revises: c8a3f3b217a5
Create Date: 2024-08-30 01:05:34.069410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3aab22d4830'
down_revision: Union[str, None] = 'c8a3f3b217a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buying', sa.Column('bought_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buying', 'bought_at')
    # ### end Alembic commands ###
