"""buying address

Revision ID: f7d859848f3a
Revises: ca3c9ed5c4e0
Create Date: 2024-06-22 14:38:03.557048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d859848f3a'
down_revision: Union[str, None] = 'ca3c9ed5c4e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buying', sa.Column('address', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buying', 'address')
    # ### end Alembic commands ###
